services:
  app:
    image: verttigo/hb-app
    container_name: HS-App
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app/backend
      - .env:/app/backend/.env

  mongodb:
    image: mongo:latest
    container_name: HS-DB
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "test"
      MONGO_INITDB_ROOT_PASSWORD: "NETksjke25852"
    volumes:
      - ./mongodb:/data/db
