services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: HS-App
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app/backend

  mongodb:
    image: mongo:latest
    container_name: HS-DB
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
